openapi: 3.0.0

paths:
  /api/v1/lirest/users:
    post:
      tags:
        - User
      description: Create new user if not exists
      summary: Create new user
      requestBody:
        $ref: "#/components/requestBodies/CreateUserRequestBody"
      responses:
        201:
          $ref: "#/components/responses/201CreateUserSuccess"
  /api/v1/lirest/users/{id}:
    get:
      security:
        - bearerAuth: []
      tags:
        - User
      description: Get user by id
      summary: Get user by id
      parameters:
        - in: path
          name: id
          description: User id
          required: true
          schema:
            type: string
      responses:
        200:
          $ref: "#/components/responses/200GetUserSuccess"
