version: '3.8'

services:
 web-api:
  container_name: lirest-api
  build:
   context: .
   dockerfile: Dockerfile.dev
  ports:
   - 3000:3000
   - 9229:9229
  environment:
   - MYSQL_HOST_NAME=mysql
   - MYSQL_PORT=${MYSQL_PORT}
  volumes:
   - ./:/app-data

 mysql:
  container_name: lirest-mysql-db
  image: mysql
  command: --default-authentication-plugin=mysql_native_password
  restart: always
  ports:
   - 3306:3306
  environment:
   - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
   - MYSQL_DATABASE=${MYSQL_DATABASE}
  volumes:
   - mysql-data:/db/mysql
volumes:
 mysql-data: