openapi: 3.0.0

components:
  schemas:
    LoginRequestDto:
      type: object
      properties:
        email:
          type: string
          format: email
          example: example@gmail.com
        password:
          type: string
          example: 123456
    RefreshTokenRequestDto:
      type: object
      properties:
        refreshToken:
          type: string
  responses:
    200LoginSuccess:
      description: Login successfully
      content:
        application/json:
          schema:
            type: object
            properties:
              accessToken:
                type: string
              refreshToken:
                type: string
    200RefreshSuccess:
      description: Refresh token successfully
      content:
        application/json:
          schema:
            type: object
            properties:
              accessToken:
                type: string
  requestBodies:
    LoginRequestBody:
      description: Login request body
      required: true
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/LoginRequestDto"
    RefreshTokenRequestBody:
      description: Refresh token request body
      required: true
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/RefreshTokenRequestDto"
