service:
  host: 127.0.0.1
  port: 3000
  baseUrl: /api/v1/lirest

mysql:
  host: localhost
  port: 3306
  username: ''
  password: ''
  database: ''

jwt:
  accessSecretKey: ''
  accessTokenExpireIn: ''
  refreshSecretKey: ''
  refreshTokenExpireIn: ''

cors:
  allowedOrigins: ''

api-docs:
  username: ""
  password: ""
