# Service configuration
service:
  host: 127.0.0.1
  port: 3000
  baseUrl: /api/v1/lirest

# Database configuration
mysql:
  host: localhost
  port: 3306
  username: root
  password: ''
  database: ''

# JWT configuration
jwt:
  accessSecretKey: ''
  accessTokenExpireIn: ''
  refreshSecretKey: ''
  refreshTokenExpireIn: ''

# Security configuration
cors:
  allowedOrigins: '*'

api-docs:
  username: ""
  password: ""