service:
  host: 127.0.0.1
  port: 3000
  baseUrl: /api/v1

mysql:
  host: ''
  port: ''
  username: ''
  password: ''
  database: ''

jwt:
  accessSecretKey: ''
  accessTokenExpireIn: ''
  refreshSecretKey: ''
  refreshTokenExpireIn: ''
