service:
  host: 127.0.0.1
  port: 3000
  baseUrl: /api/v1/lirest

mysql:
  host: localhost
  port: 3306
  username: root
  password: '123456'
  database: book_library

jwt:
  accessSecretKey: 0~N3RbbP<#cIo55
  accessTokenExpireIn: 20s
  refreshSecretKey: LCY{r2l10~?)/qu
  refreshTokenExpireIn: 30s

cors:
  allowedOrigins: http://localhost:3333

api-docs:
  username: ""
  password: ""
