openapi: 3.0.0

paths:
  /api/v1/lirest/ping:
    get:
      tags:
        - Ping
      description: Test service connection.
      summary: Ping to service.
      responses:
        200:
          description: Service on.
          content:
            text/plain:
              schema:
                type: string
                example: Pong!
        default:
          description: Unexpected error
          content:
            text/plain:
              schema:
                type: string
                example: Service off.
